### ISSUE TITLE
adapters.py import error

### ISSUE THREAD

**Issue by splaisan** [SorenKarst/longread-UMI-pipeline#11]
**chopchop** returns error at runtime when replacing the original **adapters.py** by the one here
the error occurs when trying to import **make_full_rapid_barcode_adapter** which has been moved to **make_new_full_rapid_barcode_adapter** in the replacement **adapters.py**

should we simply rename it and remove **new_** or is there more to do here?

Thanks

**Comment by SorenKarst** [comment]
Hi Stephane,

The format of the adapters.py have changed with the new version of porechop. I have made a fix for this in the developer version of the pipeline https://github.com/SorenKarst/longread-UMI-pipeline/tree/develop . This will become an official release early January.

Let me know if this does not fix the problem for you.

regards
Søren

**Comment by splaisan** [comment]
Thanks Søren
I have made a customized version of the main script to allow using other primers and other cutoffs and it finally seems to work.

I will look at your new version when it becomes the main branch and adapt my code

Thanks for the great suite of commands

PS: hope the conda yaml config file from @mdehollander is also part of your next release, it was for me of great help to install the proper versions of the dependencies.
