### ISSUE TITLE
mkdir: cannot create directory path/to/dir: no such file or directory

### ISSUE THREAD

**Issue by walexandertsu** [SorenKarst/longread-UMI-pipeline#39]
So I have longread_umi installed and mostly working. I also have a dataset that produces acceptable numbers of clusters of UMIs, and I can see the UMIs stored in the files "umi_ref_b1.fa" and "umi_ref_b2.fa." However, the pipeline breaks at the next step, where it tries to create new directories in umi_binning > read_binning>bins:

[main] Version: 0.7.17-r1188
[main] CMD: bwa samse -n 10000000 /var/lib/minknow/data/UMI_trial_3/UMI_trial_3_comb/fastq/longread-umi_analysis_round3/umi_binning/read_binning/reads_tf_umi2.fa /var/lib/minknow/data/UMI_trial_3/UMI_trial_3_comb/fastq/longread-umi_analysis_round3/umi_binning/read_binning/umi2_map.sai /var/lib/minknow/data/UMI_trial_3/UMI_trial_3_comb/fastq/longread-umi_analysis_round3/umi_binning/read_binning/umi_ref_b2.fa
[main] Real time: 23.828 sec; CPU: 22.785 sec
[10:48:34] ### Read-UMI match filtering ###
[10:48:34] Reading UMI1 match file...
[10:48:46] Reading UMI2 match file...
[10:49:01] UMI match filtering...
[10:49:02] Read orientation filtering...
[10:49:02] UMI match error filtering...
[10:49:02] UMI bin/cluster size ratio filtering...
[10:49:02] Print UMI matches...
[10:49:02] Done.
mkdir: cannot create directory ‘.//var/lib/minknow/data/UMI_trial_3/UMI_trial_3_comb/fastq/longread-umi_analysis_round3/umi_binning/read_binning/bins/job1/1’: No such file or directory
gawk: cmd. line:28: (FILENAME=- FNR=21) fatal: can't redirect to `/var/lib/minknow/data/UMI_trial_3/UMI_trial_3_comb/fastq/longread-umi_analysis_round3/umi_binning/read_binning/bins/job1/1/umi42889bins.fastq' (No such file or directory)
mkdir: cannot create directory ‘.//var/lib/minknow/data/UMI_trial_3/UMI_trial_3_comb/fastq/longread-umi_analysis_round3/umi_binning/read_binning/bins/job2/1’: No such file or directory
gawk: cmd. line:28: (FILENAME=- FNR=621) fatal: can't redirect to `/var/lib/minknow/data/UMI_trial_3/UMI_trial_3_comb/fastq/longread-umi_analysis_round3/umi_binning/read_binning/bins/job2/1/umi168704bins.fastq' (No such file or directory)
mkdir: cannot create directory ‘.//var/lib/minknow/data/UMI_trial_3/UMI_trial_3_comb/fastq/longread-umi_analysis_round3/umi_binning/read_binning/bins/job3/1’: No such file or directory
gawk: cmd. line:28: (FILENAME=- FNR=345) fatal: can't redirect to `/var/lib/minknow/data/UMI_trial_3/UMI_trial_3_comb/fastq/longread-umi_analysis_round3/umi_binning/read_binning/bins/job3/1/umi2785bins.fastq' (No such file or directory)
mkdir: cannot create directory ‘.//var/lib/minknow/data/UMI_trial_3/UMI_trial_3_comb/fastq/longread-umi_analysis_round3/umi_binning/read_binning/bins/job4/1’: No such file or directory
gawk: cmd. line:28: (FILENAME=- FNR=53) fatal: can't redirect to `/var/lib/minknow/data/UMI_trial_3/UMI_trial_3_comb/fastq/longread-umi_analysis_round3/umi_binning/read_binning/bins/job4/1/umi11765bins.fastq' (No such file or directory)
mkdir: cannot create directory ‘.//var/lib/minknow/data/UMI_trial_3/UMI_trial_3_comb/fastq/longread-umi_analysis_round3/umi_binning/read_binning/bins/job5/1’: No such file or directory
gawk: cmd. line:28: (FILENAME=- FNR=113) fatal: can't redirect to `/var/lib/minknow/data/UMI_trial_3/UMI_trial_3_comb/fastq/longread-umi_analysis_round3/umi_binning/read_binning/bins/job5/1/umi9722bins.fastq' (No such file or directory)
find: ‘/var/lib/minknow/data/UMI_trial_3/UMI_trial_3_comb/fastq/longread-umi_analysis_round3/umi_binning/read_binning/bins/*/*/’: No such file or directory

I'm _so close_ to getting this to work, so any help would be greatly appreciated. Thank you!

**Comment by SorenKarst** [comment]
Hi William, 

Thank you for reporting this bug in v0.3.2 of the pipeline. It is a mistake in the umi_binning.sh script that makes the workflow break if absolute paths are used. A fix has been implemented in the development branch of the pipeline, which can be installed as described here in issue #36 . 

Alternatively, you can use a relative path for your output directory, which should work.

P.s. I replied to your e-mail you sent a while ago, but I can see my response bounced. Can you send me a new e-mail I can send the response to?

All the best
Søren

**Comment by walexandertsu** [comment]
Hi Søren,
  I sent you an email last week, and another one just now with alternative email addresses enclosed. Let me know if my messages are getting filtered and we can figure something else out. Thanks for being so responsive to bug reports and issues!

**Comment by SorenKarst** [comment]
Hi William,

How is it going with the pipeline? Is it working for you with the work-arounds I suggested?

/Søren
