### ISSUE TITLE
Test data error: medaka stitch step file missing

### ISSUE THREAD

**Issue by rhinempi** [SorenKarst/longread-UMI-pipeline#41]
Dear Developers,

I have encountered an error running test data on the Ont_R10 dataset. 
longread_umi nanopore_pipeline  -d ont_r10_zymo_rrna.fq  -o test_r10  -v 25  -q r10_min_high_g340  -m 3500  -M 6000  -s 90   -e 90  -f CAAGCAGAAGACGGCATACGAGAT  -F AGRGTTYGATYMTGGCTCAG  -r AATGATACGGCGACCACCGAGATC  -R GACATCGAGGTGCCAAAC  -c 2  -p 2  -t 10

Error message as follow:

[16:22:42] Read orientation filtering...
[16:22:42] UMI match error filtering...
[16:22:42] UMI bin/cluster size ratio filtering...
[16:22:42] Print UMI matches...
[16:22:42] Done.

Computers / CPU cores / Max jobs to run
1:local / 28 / 1
0

Computers / CPU cores / Max jobs to run
1:local / 28 / 10

Computer:jobs running/jobs completed/%of started jobs/Average seconds to complete
local:0/10/100%/0.0s 
local:0/1/100%/1.0s 
Computers / CPU cores / Max jobs to run
1:local / 28 / 1
local:0/1/100%/1.0s 
usage: medaka stitch [-h] [--debug | --quiet]
                     [--regions REGIONS [REGIONS ...]] [--threads THREADS]
                     [--no-fillgaps]
                     inputs [inputs ...] draft output
medaka stitch: error: the following arguments are required: output
sed: can't read test_r10/raconx2_medakax1/consensus_raconx2_medakax1.fa: No such file or directory
cat: test_r10/raconx2_medakax1/consensus_raconx2_medakax1.fa: No such file or directory

I have checked the scripts. I think the *_consensus.hdf files did not generate in the former step. But, I can't figure out why.

Thanks for the help.
Liren

**Comment by rhinempi** [comment]
Oh, solved myself, thanks

**Comment by cstill3928** [comment]
Hi Liren, 

I ran into a similar issue and was wondering how you went about fixing it?

Thanks,
Chris

**Comment by rhinempi** [comment]
Hi Chris,

It is a bug in the pipeline. You need to edit one of the python scripts:
longread-UMI-pipeline/scripts/polish_medaka.sh 

Replace the section "# Stitch consensus sequences" to the following command:

```
# Stitch consensus sequences
medaka stitch \
  $OUT_DIR/consensus/*_consensus.hdf \
  $CONSENSUS_FILE \
  $OUT_DIR/consensus_${OUT_NAME}.fa
```


Best,
Liren

**Comment by cstill3928** [comment]
Thanks Liren!
