### ISSUE TITLE
How to calculate the relative abudanca of UMI amplicons?

### ISSUE THREAD

**Issue by YulinzhangSia** [SorenKarst/longread-UMI-pipeline#44]
Dear Søren,

Thanks for this wonderful work which expands my knowledge on UMI and Nanopore sequencing, while I still have a small question about quantification. 

In next-generation sequencing, in addition to labeling the original template, another important function of UMI is quantification. But in the third-generation sequencing, a lot of data was screened out from the initial UMI filtering to the final sequence cluster. In this case, how to conduct the quantification process of UMI-based amplicons?

Thanks.
Sia

**Comment by SorenKarst** [comment]
Hi Sia,

Good question. I must admit I never considered how the filtering might impact the quantification. I think the method needs to be validated before being used for quantification, and the experiments have to be setup carefully.

What we often see when we generated our UMI libraries was that we ended up tagging too many molecules, and hence ended up having too low coverage for some of the tagged molecules. Unfortunately, low coverage bias towards specific sequences, means these sequences will be underrepresented in a library with too many tagged molecules. So to trust your quantification you have to avoid this scenario and this is not always easy to control.

Best regards
Søren
