### ISSUE TITLE
Make conda installer

### ISSUE THREAD

**Issue by SorenKarst** [SorenKarst/longread-UMI-pipeline#6]
Implement installation in conda for ease and safety.

**Comment by mdehollander** [comment]
I made a conda environment file in order to make the pipeline running on our system. See here a PR that adds the environment file: https://github.com/SorenKarst/longread-UMI-pipeline/pull/7
I removed the paths in the `dependencies.sh` so that it finds the binaries installed with conda.

**Comment by SorenKarst** [comment]
Hi!

Thanks a lot for the suggestion and the pull request. We are working on the next release of the package and will include your suggestions there.

**Comment by SorenKarst** [comment]
Fixed in 4ba5bb9
