### ISSUE TITLE
ValueError found when run test_read.fq

### ISSUE THREAD

**Issue by happy1219** [SorenKarst/longread-UMI-pipeline#8]
Hello, hope you are doing well. I have tested the data in test file, but below error came out:

[xxxxx - DataIndex] Loaded 1/1 (100.00%) sample files.
Traceback (most recent call last):
  File "/home/miniconda3/envs/medaka/bin/medaka", line 11, in <module>
    sys.exit(main())
  File "/home/miniconda3/envs/medaka/lib/python3.6/site-packages/medaka/medaka.py", line 434, in main
    args.func(args)
  File "/home/miniconda3/envs/medaka/lib/python3.6/site-packages/medaka/stitch.py", line 120, in stitch
    joined = stitch_from_probs(args.inputs, regions=args.regions)
  File "/home/miniconda3/envs/medaka/lib/python3.6/site-packages/medaka/stitch.py", line 48, in stitch_from_probs
    for r in regions]
  File "/home/miniconda3/envs/medaka/lib/python3.6/site-packages/medaka/stitch.py", line 48, in <listcomp>
    for r in regions]
  File "/home/miniconda3/envs/medaka/lib/python3.6/site-packages/medaka/common.py", line 457, in from_string
    start = int(bounds)
ValueError: invalid literal for int() with base 10: 'size=118'

Any idea/suggestions? Thanks so much.

**Comment by SorenKarst** [comment]
Hi!

Interesting error. The pipeline fails in the medaka polishing step possibly due to problems with parsing the sequence headers. The problem might originate earlier in the process, so can you do the following:

Please zip the folder with the results from running the test data and upload it here (i.e. `tar -zcvf test_data.gz test_data/`)

Also can you provide a dump of the software versions you are using. Open a terminal in the  longread-UMI-pipeline/scripts/ folder and run: `source dependencies.sh; ncec_version_dump version_dump.txt`  and upload the file here.

**Comment by happy1219** [comment]
> 
> 
> Hi!
> 
> Interesting error. The pipeline fails in the medaka polishing step possibly due to problems with parsing the sequence headers. The problem might originate earlier in the process, so can you do the following:
> 
> Please zip the folder with the results from running the test data and upload it here (i.e. `tar -zcvf test_data.gz test_data/`) and then I will take a look at it.

Hi! Thanks so much for the reply! Sorry I was late because #not working during weekend :)
[test_data.gz](https://github.com/SorenKarst/longread-UMI-pipeline/files/3802324/test_data.gz)
[version_dump.txt](https://github.com/SorenKarst/longread-UMI-pipeline/files/3802325/version_dump.txt)
I have noticed you removed version dump request, but I have added it anyway. Again, thank you and waiting for your reply. 

Take care,

**Comment by SorenKarst** [comment]
Hi again.

I had a quick look and I am pretty sure medaka fails as it interprets the colon in the sequence header as region reference (hint in the release notes for v0.10.0 https://github.com/nanoporetech/medaka/tree/v0.10.0).

You have two options. A) Downgrade medaka to version 0.7.1 B) Install the development version of the pipeline: https://github.com/SorenKarst/longread-UMI-pipeline/tree/develop.  If you are using the automatic installer script you should download it from here:
https://github.com/SorenKarst/longread-UMI-pipeline/blob/develop/scripts/install_dependencies.sh. 
and use the command `bash install_dependencies.sh develop` to install.

Be aware that medaka v0.10.0 on conda seems to have a minor bug that will make it crash during tensorflow https://github.com/nanoporetech/medaka/issues/100 .  If this happens to you install version v0.9.2 or install without conda.

All the best

**Comment by happy1219** [comment]
> 
> 
> Hi again.
> 
> I had a quick look and I am pretty sure medaka fails as it interprets the colon in the sequence header as region reference (hint in the release notes for v0.10.0 https://github.com/nanoporetech/medaka/tree/v0.10.0).
> 
> You have two options. A) Downgrade medaka to version 0.7.1 B) Install the development version of the pipeline: https://github.com/SorenKarst/longread-UMI-pipeline/tree/develop. If you are using the automatic installer script you should download it from here:
> https://github.com/SorenKarst/longread-UMI-pipeline/blob/develop/scripts/install_dependencies.sh.
> and use the command `bash install_dependencies.sh develop` to install.
> 
> Be aware that medaka v0.10.0 on conda seems to have a minor bug that will make it crash during tensorflow [nanoporetech/medaka#100](https://github.com/nanoporetech/medaka/issues/100) . If this happens to you install version v0.9.2 or install without conda.
> 
> All the best

Option A worked. Really appreciated it. 
Take care,

**Comment by SorenKarst** [comment]
Great! Thank you for pointing this out.

I will leave the issue open until there is a permanent fix.
